import { readFile } from 'node:fs/promises';

// The layout and personal writing come from the existing Netlify portfolio.
// Artwork and project links are generated once; the flight moves those same links.
export async function homepage({root, projects, retreat, cialo, milkplexity, cleanWordmark, image, esc, origin}) {
  const milk = slug => milkplexity.find(p => p.slug === slug);
  const all = [
    ...projects.map(p => p.slug === 'training-room-fitness-retreat' ? {...p, image:retreat, year:'2027', description:'Branding for my dad’s fitness retreat in Nosara, Costa Rica. The 2027 identity brings together retro lettering, coastal color, and hibiscus flowers.', gallery:[p.image]} : p),
    {slug:'cialo',title:'Ciało',category:{label:'Personal Branding'},year:'2026',image:cialo.find(a=>a.slug==='color-amber'),description:'My own identity, built around a sculptural ł. A wordmark, an icon, five color studies, and the original animation.',tags:['Brand Identity','Motion'],fullPage:true},
    {slug:'milkplexity',title:'Milkplexity',category:{label:'Personal Branding'},year:'2026',image:milk('icon'),description:'The Milkplexity identity and Milkplexity Learn. A pouring-glass symbol, cyan, white, and rounded lettering.',tags:['Brand Identity'],fullPage:true}
  ];
  const featuredSlugs = ['training-room-fitness-retreat','cialo','milkplexity','row-for-hope-2026','american-250-team-challenge'];
  const featured = featuredSlugs.map(slug=>all.find(p=>p.slug===slug));
  const archive = all.filter(p=>!featuredSlugs.includes(p.slug));
  const row = featured[3], american = featured[4];
  const year = p => p.yearOld ? `${esc(p.yearOld)} artwork / ${esc(p.year)} event` : esc(p.year);
  const projectLink = (slug,label) => `<a class="story-link" href="projects/${slug}/">${label} <span aria-hidden="true">↗</span></a>`;
  const cover = (p,item,classes='',label=p.title) => `<a class="flight-art ${classes}" data-flight="${p.slug}" href="projects/${p.slug}/" aria-label="Explore ${esc(label)}">${image(item,'',{eager:p===featured[0],sizes:'(max-width: 760px) 90vw, 60vw'})}</a>`;
  const study = (item,slug,anchor,label,classes='') => `<a class="study-art ${classes}" href="projects/${slug}/${anchor}" aria-label="${esc(label)}">${image(item,'',{sizes:'(max-width:760px) 42vw, 26vw'})}<span>${esc(label)} <span aria-hidden="true">↗</span></span></a>`;
  const caseHead = (n,discipline,title,id) => `<header class="case-heading"><p class="case-number">${n} <span aria-hidden="true">/</span> ${discipline}</p><h2 id="${id}">${title}</h2></header>`;
  const features = `<article class="case-story retreat-story" data-featured-project="training-room-fitness-retreat" aria-labelledby="retreat-title">
<div class="retreat-layout">${cover(featured[0],retreat,'retreat-cover','Training Room Fitness Retreat 2027')}<div class="story-copy">${caseHead('01','Event identity','The Training Room<span>Nosara, 2027.</span>','retreat-title')}<p class="story-intro">A little family connection.<br>A lot of Costa Rica.</p><p>Branding for my dad’s fitness retreat. Turquoise lettering, layered sunset colors, and hibiscus flowers bring the 2027 identity together.</p><dl class="story-facts"><div><dt>Made for</dt><dd>Fitness retreat</dd></div><div><dt>Place & edition</dt><dd>Nosara, Costa Rica · 2027</dd></div></dl>${projectLink(featured[0].slug,'Explore the retreat identity')}</div></div>
<p class="art-caption">The 2027 retreat artwork, shown in full.</p></article>

<article class="case-story cialo-story" data-featured-project="cialo" aria-labelledby="cialo-title">
<div class="story-heading-row">${caseHead('02','Personal identity','Ciało','cialo-title')}<div class="heading-note"><p>A sculptural ł. Light, depth, and a character of its own.</p>${projectLink('cialo','Explore the complete identity')}</div></div>
${cover(featured[1],cleanWordmark,'cialo-cover')}
<div class="cialo-studies">${['symbol-flat','symbol-faceted','symbol-wireframe'].map((slug,i)=>study(cialo.find(a=>a.slug===slug),'cialo','#symbol',['The silhouette','The sculptural form','The wireframe'][i])).join('')}</div>
<div class="cialo-notes"><p>One form, from a flat mark to an illuminated symbol. The full identity includes the app icon, five color studies, and the original animated wordmark.</p><details class="showcase-motion"><summary>Play the original animation <span aria-hidden="true">＋</span></summary><div class="showcase-player"><iframe src="assets/cialo/interactive/index.html" title="Ciało original animation with playback controls" loading="lazy" referrerpolicy="no-referrer"></iframe></div><a href="projects/cialo/#motion">Video & original files <span aria-hidden="true">↗</span></a></details></div></article>

<article class="case-story milk-story" data-featured-project="milkplexity" aria-labelledby="milk-title">
<div class="story-heading-row">${caseHead('03','Personal identity','Milkplexity','milk-title')}<div class="heading-note"><p>A familiar pour. A different side of my own work.</p>${projectLink('milkplexity','Explore Milkplexity')}</div></div>
<div class="milk-composition"><div class="milk-main">${cover(featured[2],milk('main-logo'),'milk-cover')}<p class="art-caption">The main identity — a pouring glass and a cyan-and-white wordmark.</p></div><div class="milk-companions">${study(milk('icon'),'milkplexity','#milk-icon','The standalone icon','milk-icon')}${study(milk('learn'),'milkplexity','#learn','Milkplexity Learn','milk-learn')}</div></div></article>

<article class="case-story row-story" data-featured-project="row-for-hope-2026" aria-labelledby="row-title">
<div class="row-layout"><div class="story-copy">${caseHead('04','Event identity','Row for Hope<span>2026 / 2027.</span>','row-title')}<p class="story-intro">A mark for a cause<br>worth showing up for.</p><p>A shield-style identity for Hero Events’ Brain Cancer Awareness charity event, designed to convey strength and purpose.</p><p class="event-note">Created for 2026. The event was postponed to 2027, with this identity carrying forward.</p>${projectLink(row.slug,'Explore Row for Hope')}</div>${cover(row,row.image,'row-cover','Row for Hope 2026 / 2027')}</div></article>

<article class="case-story american-story" data-featured-project="american-250-team-challenge" aria-labelledby="american-title">
<div class="story-heading-row">${caseHead('05','Event graphics & print','The American 250','american-title')}<div class="heading-note"><p>For The Training Room’s July 4th team challenge, marking America’s 250th.</p>${projectLink(american.slug,'See the artwork & shirts')}</div></div>
<div class="american-composition"><div class="american-poster">${cover(american,american.image,'american-cover')}<p class="art-caption">The event artwork. Flag-filled numerals and vintage Americana lettering.</p></div><div class="american-print">${study(american.gallery[1],american.slug,'','Front & back shirt artwork')}<p class="print-note">From the event mark to shirt artwork for the challenge.</p>${study(american.gallery[0],american.slug,'','The front graphic','american-front')}</div></div></article>`;
  const archiveMarkup = `<section class="archive-section container" id="archive" aria-labelledby="archive-heading"><div class="archive-heading"><div><p class="case-number">From the archive</p><h2 id="archive-heading">Earlier work & side projects.</h2></div><p>The businesses, podcasts, teams, and ideas that came along the way.</p></div><details class="archive-disclosure"><summary>Browse ${archive.length} more projects <span aria-hidden="true">＋</span></summary><div class="archive-grid">${archive.map(p=>`<a class="archive-project" data-archive-project="${p.slug}" data-preview="${p.slug}" href="projects/${p.slug}/" aria-label="Explore ${esc(p.title)}">${image(p.image,'',{sizes:'(max-width:760px) 72px, 100px',alt:''})}<div><h3>${esc(p.title)}</h3><p>${esc(p.category.label)} · ${year(p)}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></details></section>`;
  // Only the selected five belong to the mobile motion sequence.
  const mobileSet = featured.map(p=>`<div class="m-card">${image(p.image,'',{sizes:'182px',alt:''})}</div>`).join('');
  const mobile = `<div class="m-strip" aria-hidden="true" inert><div class="m-tilt"><div class="m-track"><div class="m-set">${mobileSet}</div><div class="m-set">${mobileSet}</div></div></div></div>`;
  const templates = archive.map(p=>`<template id="preview-${p.slug}"><div class="modal-media"><div class="modal-figure">${image(p.image,'',{sizes:'(max-width:760px) 90vw, 44vw',extra:' data-preview-image',eager:false})}</div>${p.gallery?.length?`<div class="modal-thumbs" role="group" aria-label="Artwork views">${[p.image,...p.gallery].map((a,i)=>`<button type="button" data-preview-src="${a.variants?.at(-1)?.src||a.src}" data-preview-alt="${esc(a.alt)}" aria-label="Show ${esc(a.alt)}" aria-pressed="${i===0}">${image(a,'',{sizes:'54px',alt:''})}</button>`).join('')}</div>`:''}</div><div class="modal-body"><div class="modal-meta"><span>${esc(p.category.label)}</span><span class="yr">${year(p)}</span></div><h2 class="modal-title" id="modalTitle">${esc(p.title)}</h2><p class="modal-desc">${esc(p.description)}</p><div class="modal-tools">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="modal-foot"><a class="btn btn-green" href="projects/${p.slug}/">View full project <span aria-hidden="true">↗</span></a><a class="modal-contact" href="mailto:ianmilkowski@gmail.com">Get in touch</a></div><p class="preview-status" role="status" data-preview-status></p></div></template>`).join('\n');
  let body = await readFile(new URL('../src/home.html', import.meta.url),'utf8');
  body = body.replace('{{COUNT_2}}',projects.filter(p=>p.category.id==='podcast-media').length).replace('{{COUNT_4}}',projects.filter(p=>p.category.id==='charity-events').length).replace('{{COUNT_6}}',projects.filter(p=>p.category.id==='business-branding').length+2).replace('{{COUNT_3}}',projects.filter(p=>p.category.id==='passion-project').length).replace('{{FEATURES}}',features).replace('{{ARCHIVE}}',archiveMarkup).replace('{{MOBILE_STRIP}}',mobile);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#0a0a0a"><title>Ian Milkowski | Creative Portfolio</title><meta name="description" content="Brand identity, event graphics, and media design by Ian Milkowski. Explore brand identities, including Ciało, Milkplexity, and The Training Room."><link rel="canonical" href="${origin}"><meta property="og:title" content="Ian Milkowski | Creative Portfolio"><meta property="og:description" content="Turning rough ideas into marks people remember, for brands, events, and causes."><meta property="og:type" content="website"><meta property="og:url" content="${origin}"><meta property="og:image" content="${origin}assets/projects/og-card.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/home.css"><script src="assets/home.js" defer></script><script src="assets/flight.js" type="module"></script></head><body class="static">${body}<dialog class="modal" id="project-preview" aria-labelledby="modalTitle"><div class="modal-panel"><button type="button" class="modal-close" data-preview-close aria-label="Close project" autofocus>×</button><div class="preview-content"></div></div></dialog>${templates}</body></html>\n`;
}
