import { readFile } from 'node:fs/promises';

// The layout and personal writing come from the existing Netlify portfolio.
// Artwork and project links are generated once; the flight moves those same links.
export async function homepage({root, projects, retreat, cialo, milkplexity, cleanWordmark, image, esc, origin}) {
  const milk = slug => milkplexity.find(p => p.slug === slug);
  const all = [
    ...projects.map(p => p.slug === 'training-room-fitness-retreat' ? {...p, image:retreat, year:'2027', description:'Branding for my dad’s fitness retreat in Nosara, Costa Rica. The 2027 identity brings together retro lettering, coastal color, and hibiscus flowers.', gallery:[p.image]} : p),
    {slug:'cialo',title:'Ciało',category:{label:'Personal Branding'},year:'2026',image:cialo.find(a=>a.slug==='color-amber'),description:'My own identity, built around a sculptural ł. A wordmark, an icon, five color studies, and the original animation.',tags:['Brand Identity','Motion'],fullPage:true},
    {slug:'milkplexity',title:'Milkplexity',category:{label:'Personal Branding'},year:'2026',image:milk('icon'),description:'The Milkplexity identity and Milkplexity Learn. A pouring-glass symbol, cyan, white, and rounded lettering.',tags:['Brand Identity'],fullPage:true}
  ];
  // Lead with the new personal identities, then preserve the original project order.
  all.unshift(...all.splice(-2));
  const year = p => p.yearOld ? `<s aria-label="Originally ${esc(p.yearOld)}">${esc(p.yearOld)}</s> <span aria-label="Postponed to ${esc(p.year)}">${esc(p.year)}</span>` : esc(p.year);
  const tiles = all.map((p,i)=>`<a class="tile${p.feature?' feature':''}" href="projects/${p.slug}/"${p.fullPage?'':` data-preview="${p.slug}"`} aria-label="Explore ${esc(p.title)}">${image(p.image,'',{eager:i<3,sizes:'(max-width: 760px) 90vw, (max-width: 1100px) 46vw, 32vw',alt:''})}<div class="scrim" aria-hidden="true"></div><div class="label"><span class="tt">${esc(p.title)}</span><span class="tc">${esc(p.category.label)} · ${year(p)}</span></div></a>`).join('\n');
  // A decorative mobile strip previews the same work; all accessible links live in the grid.
  const mobileArt = ['cialo','milkplexity','american-250-team-challenge','training-room-fitness-retreat','fuming-takes','behind-the-venue'].map(slug=>all.find(p=>p.slug===slug));
  const mobileSet = mobileArt.map(p=>`<div class="m-card">${image(p.image,'',{sizes:'182px',alt:''})}</div>`).join('');
  const mobile = `<div class="m-strip" aria-hidden="true" inert><div class="m-tilt"><div class="m-track"><div class="m-set">${mobileSet}</div><div class="m-set">${mobileSet}</div></div></div></div>`;
  const features = `<section class="identity-stories container" aria-labelledby="identity-heading"><div class="sec-head"><div class="pill"><i></i>A closer look</div><h2 id="identity-heading">Two identities.<br><em>A world of my own.</em></h2></div>
<article class="identity-feature identity-cialo"><a class="identity-art" href="projects/cialo/" aria-label="Explore the Ciało identity and animation">${image(cleanWordmark,'',{sizes:'(max-width:760px) 90vw, 84vw'})}<span class="identity-art-note">Identity in motion <span aria-hidden="true">↗</span></span></a><div class="identity-caption"><div><p class="identity-kicker">Personal identity / 2026</p><h3><a href="projects/cialo/">Ciało</a></h3></div><p>A sculptural ł, luminous color, and the original animated wordmark. My own brand, from symbol to signature.</p><a class="identity-link" href="projects/cialo/#motion">Explore the identity & motion <span aria-hidden="true">↗</span></a></div></article>
<article class="identity-feature identity-milk"><div class="milk-pair"><a class="identity-art" href="projects/milkplexity/" aria-label="Explore the Milkplexity main identity">${image(milk('main-logo'),'',{sizes:'(max-width:760px) 90vw, 60vw'})}</a><a class="identity-art milk-learn" href="projects/milkplexity/#learn" aria-label="Explore Milkplexity Learn">${image(milk('learn'),'',{sizes:'(max-width:760px) 60vw, 25vw'})}</a></div><div class="identity-caption"><div><p class="identity-kicker">My own projects / Branding</p><h3><a href="projects/milkplexity/">Milkplexity</a></h3></div><p>A pouring glass. A familiar name. The main identity, the standalone icon, and Milkplexity Learn.</p><a class="identity-link" href="projects/milkplexity/">Explore Milkplexity <span aria-hidden="true">↗</span></a></div></article></section>`;
  const templates = all.filter(p=>!p.fullPage).map(p=>`<template id="preview-${p.slug}"><div class="modal-media"><div class="modal-figure">${image(p.image,'',{sizes:'(max-width:760px) 90vw, 44vw',extra:' data-preview-image',eager:false})}</div>${p.gallery?.length?`<div class="modal-thumbs" role="group" aria-label="Artwork views">${[p.image,...p.gallery].map((a,i)=>`<button type="button" data-preview-src="${a.variants?.at(-1)?.src||a.src}" data-preview-alt="${esc(a.alt)}" aria-label="Show ${esc(a.alt)}" aria-pressed="${i===0}">${image(a,'',{sizes:'54px',alt:''})}</button>`).join('')}</div>`:''}</div><div class="modal-body"><div class="modal-meta"><span>${esc(p.category.label)}</span><span class="yr">${year(p)}</span></div><h2 class="modal-title" id="modalTitle">${esc(p.title)}</h2><p class="modal-desc">${esc(p.description)}</p><div class="modal-tools">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="modal-foot"><a class="btn btn-green" href="projects/${p.slug}/">View full project <span aria-hidden="true">↗</span></a><a class="modal-contact" href="mailto:ianmilkowski@gmail.com">Get in touch</a></div><p class="preview-status" role="status" data-preview-status></p></div></template>`).join('\n');
  let body = await readFile(new URL('../src/home.html', import.meta.url),'utf8');
  body = body.replace('{{PROJECT_COUNT}}',all.length).replace('{{COUNT_2}}',projects.filter(p=>p.category.id==='podcast-media').length).replace('{{COUNT_4}}',projects.filter(p=>p.category.id==='charity-events').length).replace('{{COUNT_6}}',projects.filter(p=>p.category.id==='business-branding').length+2).replace('{{COUNT_3}}',projects.filter(p=>p.category.id==='passion-project').length).replace('{{TILES}}',tiles).replace('{{FEATURES}}',features).replace('{{MOBILE_STRIP}}',mobile);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#0a0a0a"><title>Ian Milkowski | Creative Portfolio</title><meta name="description" content="Brand identity, event graphics, and media design by Ian Milkowski. Explore brand identities, including Ciało, Milkplexity, and The Training Room."><link rel="canonical" href="${origin}"><meta property="og:title" content="Ian Milkowski | Creative Portfolio"><meta property="og:description" content="Turning rough ideas into marks people remember, for brands, events, and causes."><meta property="og:type" content="website"><meta property="og:url" content="${origin}"><meta property="og:image" content="${origin}assets/projects/og-card.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/home.css"><script src="assets/home.js" defer></script><script src="assets/flight.js" type="module"></script></head><body class="static">${body}<dialog class="modal" id="project-preview" aria-labelledby="modalTitle"><div class="modal-panel"><button type="button" class="modal-close" data-preview-close aria-label="Close project" autofocus>×</button><div class="preview-content"></div></div></dialog>${templates}</body></html>\n`;
}
